services:

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5000:5000"
    environment:
      - API_GATEWAY_URL=http://api-gateway:8000
    depends_on:
      - api-gateway

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - auth-service
    # Aquí puedes agregar los otros servicios base

  # Microservicio de Autenticación
  auth-service:
    build: ./services/authentication
    container_name: auth-service
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=mongodb://auth-db:27017/auth_db
    depends_on:
      - auth-db

  # Base de datos para el servicio de autenticación
  auth-db:
    image: mongo:latest
    container_name: auth-db
    ports:
      - "27017:27017"
    volumes:
      - auth_data:/data/db

  # --- Plantillas de Microservicios ---
  
  # Microservicio de pagos
  pagos-service:
    build: ./services/pagos 
    container_name: pagos-service
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@pagos-db:5432/pagos_db
    depends_on:
      pagos-db:
        condition: service_healthy

  # Base de datos para el servicio de pagos
  pagos-db:
     image: postgres:latest
     container_name: pagos-db
     environment:
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=postgres
       - POSTGRES_DB=pagos_db
       - POSTGRES_HOST_AUTH_METHOD=trust # Para permitir conexiones locales
     ports:
       - "5434:5432"  # Puerto externo 5434 para evitar conflicto
     volumes:
       - pagos_data:/var/lib/postgresql
     healthcheck:
       test: ["CMD-SHELL", "pg_isready -U postgres -d pagos_db"]
       interval: 5s
       timeout: 5s
       retries: 5

  # Microservicio de pedidos
  pedidos-service:
    build: ./services/pedidos 
    container_name: pedidos-service
    ports:
      - "8003:8003"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@pedidos-db:5432/pedidos_db
    depends_on:
      pedidos-db:
        condition: service_healthy


  # Base de datos para el servicio de pedidos
  pedidos-db:
    image: postgres:latest
    container_name: pedidos-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pedidos_db
      - POSTGRES_HOST_AUTH_METHOD=trust # Para permitir conexiones locales
    ports:
      - "5432:5432"  # Puerto 5432 para pedidos (diferente a pagos)
    volumes:
      - pedidos_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pedidos_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Microservicio de productos
  productos-service:
    build: ./services/productos 
    container_name: productos-service
    ports:
      - "8004:8004"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@productos-db:5432/productos_db
    depends_on:
      productos-db:
        condition: service_healthy

  # Base de datos para el servicio de productos
  productos-db:
    image: postgres:latest
    container_name: productos-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=productos_db
      - POSTGRES_HOST_AUTH_METHOD=trust # Para permitir conexiones locales
    ports:
      - "5433:5432"  # Puerto 5432 para productos (diferente a pagos)
    volumes:
      - productos_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d productos_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  auth_data:
  pagos_data:
  pedidos_data:
  productos_data:
